name: Deploy to GitHub Spaces

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_streamlit.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_streamlit.txt

    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short

    - name: Deploy to GitHub Spaces
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: github/spaces-deploy@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        spaces-config: spaces.json